server:
  port: 8761


security:
  basic:
    enabled: true # 启用身份认证
  user:
    name: vinohsueh # 定义用户名
    password: lby1357982 # 定义密码

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false    #通过registerWithEurekafetchRegistry:false来表明自己是一个eureka server.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/